### ISSUE TITLE
Test failed by using torch

### ISSUE THREAD

**Issue by dengfuping** [antvis/tools#3]
- CI link: https://travis-ci.org/antvis/g/builds/577663248

![image](https://user-images.githubusercontent.com/14918822/63830829-b7ac0d80-c99f-11e9-81ca-c56487e43196.png)

**Comment by hustcc** [comment]
使用 npm run test，而不是使用 test-live，试试看。

另外，建议 package.json 中的按照规范来保持一致？包括 tslint、pprettier。可以直接参考 scale 的写法。

**Comment by dengfuping** [comment]
@hustcc 
- `npm run test` 也是同样的问题，见 [CI 链接](https://travis-ci.org/antvis/g/builds/577677358):
![image](https://user-images.githubusercontent.com/14918822/63831848-238f7580-c9a2-11e9-8cf8-7c58d7d34f2e.png)
> 另外，建议 package.json 中的按照规范来保持一致？包括 tslint、pprettier。可以直接参考 scale 的写法。

- 加上 CI 后就会做统一。

**Comment by dengfuping** [comment]
- 根据 [travis 文档](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui)，在 `travis` 中跑 GUI 相关的测试时，需要安装 `xvfb` 这个包。 `.travis.yml` 可以参考以下配置:
```yml
language: node_js
node_js:
  - stable
env:
  matrix:
    - TEST_TYPE=ci
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - |
    if [ "$TEST_TYPE" = ci ]; then
      npm run ci
    fi

```
